# Generated by Django 4.0.1 on 2022-06-15 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idCarrito', models.AutoField(primary_key=True, serialize=False)),
                ('totalCarrito', models.IntegerField(verbose_name='Total')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('idCategoriaProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=100, verbose_name='Nombre categoria')),
            ],
            options={
                'verbose_name': 'Categoria producto',
                'verbose_name_plural': 'Categorias productos',
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('idDescuento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDescuento', models.CharField(max_length=100, verbose_name='Nombre descuento')),
                ('descripcion', models.CharField(max_length=254, verbose_name='Descripción descuento')),
                ('porcentajeDescuento', models.IntegerField(verbose_name='porcentajeDescuento')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('idDetallePedido', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.ImageField(upload_to='', verbose_name='Total pedido')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPublico',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('descripcion', models.CharField(max_length=254, verbose_name='Descripción')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock disponible')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.categoriaproducto')),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.descuento')),
            ],
            options={
                'verbose_name': 'Producto Publico',
                'verbose_name_plural': 'Productos Publicos',
            },
        ),
        migrations.CreateModel(
            name='ItemsPedido',
            fields=[
                ('idItemsPedido', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('detallePedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.detallepedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.productopublico')),
            ],
            options={
                'verbose_name': 'Item del pedido',
                'verbose_name_plural': 'Items del pedido',
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('idItemCarrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.productopublico')),
            ],
            options={
                'verbose_name': 'Item del carrito',
                'verbose_name_plural': 'Items del carrito',
            },
        ),
    ]
