# Generated by Django 4.0.1 on 2022-06-15 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_productopublico_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopublico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ventas', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='productopublico',
            name='descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.descuento'),
        ),
    ]
