# Generated by Django 4.0.1 on 2022-06-18 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_remove_detallepedido_fechamodificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='total',
        ),
    ]
